query orderForm @context(scope: "private") {
  orderForm {
    orderFormId
    value
    items {
      id
      name
      imageUrl
      detailUrl
      skuName
      quantity
      sellingPrice
    }
  }
}
